device: "cpu"
savefig: False

VAEncoder:
  in_channels: 3
  latent_channels: 4
  in_channels_params: [3, 96, 128, 192]
  out_channels_params: [96, 128, 192,256]
  kernel_params: [5, 3, 3, 3]
  pooling_layers: [2, 4]
  activation_function: "relu"

Attention:
  latent_channels: 4
  cond_dim: 256

Image:
  tissue_mask_params: 
    kernel_size: 20
    sigma: 20
    downsample: 8
    background_gray_threshold: 220

  patch_extraction_params:
    patch_size: 128
    patch_tissue_threshold: 0.7
    is_visualize: False